### ISSUE TITLE
Ability to see people's profile

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#103]
When pressing on a person (Like co-creator)
Ability to see bio or other info on that person in a small tooltip

## Design
<img width="237" alt="Screen Shot 2020-08-26 at 17 55 49" src="https://user-images.githubusercontent.com/1032526/91319837-838f4680-e7c5-11ea-9500-706f3705ffb3.png">

@aerugo @gustavlrsn Do you like that feature and the suggested design (Ignore the edit icon) ?

**Comment by aerugo** [comment]
We should have a user profile be set for Plato as a whole and also be displayed on Realities. It could be set on Dreams though and queried from Realties. How far did we get with this in #127 ? Is it very out of date now?

**Comment by aerugo** [comment]
We will probably do this, but will define with UX overhaul
