### ISSUE TITLE
It should be clearer where we are

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#107]
It's not clear where we are - which organization - which event - which dream
Use a breadcrumb component of some kind

Org > Project > Dream Title 

@gustavlrsn @NirBenita Let me know your thoughts

<img width="343" alt="Screen Shot 2020-08-26 at 18 22 45" src="https://user-images.githubusercontent.com/1032526/91324701-0535a300-e7cb-11ea-9dd4-e19578f2380f.png">

**Comment by gustavlrsn** [comment]
This is the current state of figuring out where you are:

![Skärmavbild 2020-09-01 kl  11 32 29](https://user-images.githubusercontent.com/1552194/91834314-29203b00-ec48-11ea-8abd-b9de51b2c896.png)

The only thing I feel is not strikingly obvious is the organization, you have to look in the url or look at the logo or hover over the logo to get the organization title. But at the same time as a user/visitor/dreamer you probably already know what organization or context you are visiting, as you got here from some other place and context etc, and there is no UI to go between different organizations, they are all isolated islands.

I'm also not sure where or how to add a breadcrumb, just adding it "on top of" what is already there would introduce a bit of redundant information/elements. Reformatting the things in the header to be more like a breadcrumb could be done in desktop, but could also take up a lot of space and feel cluttered?

**Comment by rootux** [comment]
Valid points.
Another point is perhaps in mobile that would be an overkill and would take
too much space.
@nir would love to see what you can come up with.

**Comment by rootux** [comment]
@NirBenita drafted this breadcrumb

So the home button is to go to the organization main screen. I guess we can use that in the case where we don't have the organization logo or otherwise use the organization logo

![image](https://user-images.githubusercontent.com/1032526/95353124-99674f80-08cb-11eb-8908-a3ae304cacdd.png)

**Comment by rootux** [comment]
@benitanir If I'm an admin - I also have 3 dots to set event settings. What should I do with those?

Both views are the same but have a look at the current state:

Event view
<img width="1440" alt="Screen Shot 2020-10-11 at 17 28 35" src="https://user-images.githubusercontent.com/1032526/95681205-3b967880-0be7-11eb-9a71-cc91a241c55b.png">

Dream view
<img width="1440" alt="Screen Shot 2020-10-11 at 17 28 40" src="https://user-images.githubusercontent.com/1032526/95681224-5537c000-0be7-11eb-947d-994bfa2ad223.png">

**Comment by rootux** [comment]
Done
