### ISSUE TITLE
Email template for an organization

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#108]
When user signs up to an organization - Send an email - using default html template that can be set by admins

Something like that
https://zurb.com/playground/responsive-email-templates

@aerugo @gustavlrsn @Nirbenita let me know your thoughts

**Comment by aerugo** [comment]
This would be really useful, yes. It's not a priority on our roadmap to allow for custom HTML templates, but if someone was to make a good implementation we would merge it.

**Comment by aerugo** [comment]
Closing this in a general issue clean-up.
