### ISSUE TITLE
Prefunding not working as expected

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#114]
I've tried to pre-fund this Dream: https://dreams.blivande.com/kulturbryggan-2020/5f4d45db707e600008f0742e
It's not working as expected:

* When clicking on "prefund" nothing happens, until I click the three dots again, which brings up the modal
* When I try to issue 1045000 grants of 1 SEK each, nothing happens

**Comment by gustavlrsn** [comment]
This should now be fixed
