### ISSUE TITLE
Cant enter into an event from organization

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#118]
Open an organization main page.
Click on any event.
Expected behavior - The event page should open.
Current behavior - Nothing happened.

<img width="463" alt="Screen Shot 2020-09-10 at 0 27 42" src="https://user-images.githubusercontent.com/1032526/92656903-85e0bd00-f2fc-11ea-89c6-34dd3375e1c1.png">

**Comment by gustavlrsn** [comment]
Fixed in 060525d
