### ISSUE TITLE
Changing the order of guidelines and custom fields is broken

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#120]
It doesn't work to change the order of guidelines.

**Comment by aerugo** [comment]
Confirming that this is still an issue.

**Comment by aerugo** [comment]
https://user-images.githubusercontent.com/7785081/113165344-26b7ab00-9242-11eb-85f2-572145181da3.mov

Screen capture of bug.

**Comment by Powersource** [comment]
This is really inconsistent to reproduce. My best guess is that it's somehow caused by latency since I have a vague feeling so far that it's easier to reproduce in production than locally. But even in production it's not super consistent, and turning on artifical throttling in the dev tools doesn't seem to make it reproduce more.

**Comment by Powersource** [comment]
Ok I think there might be a bug in the sorting code

here's a request that i think was unsuccessful

```json
{"data":{"setCustomFieldPosition":{"id":"6073472f7f8d73b368f8c0d0","customFields":[{"id":"607598a58ffac9188bb439ea","name":"1 custom","description":"a","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319525493,"__typename":"CustomField"},{"id":"607598aa8ffac9188bb439eb","name":"2 c","description":"b","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319530671,"__typename":"CustomField"},{"id":"607598b48ffac9188bb439ec","name":"3 f","description":";","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319540205,"__typename":"CustomField"},{"id":"607598c48ffac9188bb439ed","name":"4 h","description":"j","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319556965,"__typename":"CustomField"}],"__typename":"Event"}}}
```

here's one that was successful
```json
{"data":{"setCustomFieldPosition":{"id":"6073472f7f8d73b368f8c0d0","customFields":[{"id":"607598a58ffac9188bb439ea","name":"1 custom","description":"a","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319525493,"__typename":"CustomField"},{"id":"607598aa8ffac9188bb439eb","name":"2 c","description":"b","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319530671,"__typename":"CustomField"},{"id":"607598b48ffac9188bb439ec","name":"3 f","description":";","type":"TEXT","isRequired":false,"position":1000,"isShownOnFrontPage":false,"createdAt":1618319540205,"__typename":"CustomField"},{"id":"607598c48ffac9188bb439ed","name":"4 h","description":"j","type":"TEXT","isRequired":false,"position":1000.5,"isShownOnFrontPage":false,"createdAt":1618319556965,"__typename":"CustomField"}],"__typename":"Event"}}}
```

**Comment by Powersource** [comment]
I think I've figured it out! All items start out at position 1000 so sorting from 1,2,3 to 1,3,2 by moving the 3 doesn't work, you can't squeeze the 3 inbetween two 1000's. You can however move the 2 to the end, because then the 2 simply gets position 1001. And when you've shuffled stuff around long enough, the guidelines have diverse positions and don't collide, so the bug "disappears" over time.

**Comment by Powersource** [comment]
Also the logic for this is duplicated in the 2 components DraggableGuidelines and DraggableCustomFields, I'll refactor that as well in the PR.

**Comment by aerugo** [comment]
Is the fix live @gustavlrsn? Still having problems with this.

**Comment by Powersource** [comment]
@aerugo I forgot to mention. Old guidelines/custom fields might still have colliding positions (and you'll have trouble reordering them). Either move them around a bit (to the top or bottom where they'll get their positions incremented/decremented), or simply delete and recreate them.
