### ISSUE TITLE
Filtering/sorting of dreams

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#13]
### Filtering/sorting

As a user, I'd like to be able to filter dreams on 
- [x] free-text
- [x] tags
- [ ] funded/not funded
- ...

and sort on:
- [ ] random (a seeded random sort would be good so that the sort order is remained, easier to navigate etc)
- [ ] percentage funded
- ...

**Comment by aerugo** [comment]
Closing this in a general issue clean-up.
