### ISSUE TITLE
Change of text

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#130]
Instead of "Magic link sent" - WHT-IF requested to use "Are you ready to start dreaming?"
We have a few options:
1. We change it globally.
2. We fork and change on our deploy (I would like to avoid that).
3. We somehow give an option for the "Org admins" to modify the system texts (Something like i18n). What's your thoughts on that?
4. Other thoughts?

I know you also talked about changing a few other concept (Like from dream to project or something similar).

**Comment by rootux** [comment]
Same instead of "finish sign up" they suggested "let's suit you up"

**Comment by aerugo** [comment]
Essentially same as #141
