### ISSUE TITLE
Confetti / Confirmation on finish creating profile (That is sign up) + on dream creation

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#131]
A success notification for the user on:
1. User finish setting up his profile
2. User created a dream (Or published a dream).

That would serve the purpose of use understanding he completed the sign up + created a dream.
Right now it's not clear to the users as the click on "Join" then it get "replaced" to Create a dream - should be clearer that the user success in sign up.

Right now the user simply see "New Dream" which can be confusing to some

<img width="884" alt="Screen Shot 2020-11-01 at 18 22 57" src="https://user-images.githubusercontent.com/1032526/97808389-489b0a80-1c6f-11eb-9f78-b4b74046902c.png">

We can use this one -> https://www.npmjs.com/package/react-confetti

**Comment by aerugo** [comment]
Success notifications are something that @skoteskote also brought up from a user test. I'm bumping this and putting it on the roadmap.

**Comment by rootux** [comment]
3. User clicks on "Join organization" - it immediately changes to "Create Dream".
Here a "Welcome onboard" notification might work
