### ISSUE TITLE
Edit Pencils should be static[?]

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#132]
Some of the people who tested the system (Boomers profile) found it difficult to find the Edit pencil and edit it - They suggested to keep all the edit pencils static and visible.
Personally I disagree as that is a bit uglier but might gives more accessibility - what's your take on that?

<img width="867" alt="Screen Shot 2020-11-01 at 18 24 30" src="https://user-images.githubusercontent.com/1032526/97808437-839d3e00-1c6f-11eb-96b8-cab8836c4fd5.png">

**Comment by gustavlrsn** [comment]
This is now fixed, edit pencils are static for better accessibility
