### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#134]
WHT IF suggested to have a "Red" dot marking that a field is required.

I remember we had a few discussion on what does "Required" means.
For the end user - probably it would be best to mark it as required before publishing[?] - that way they would get an error saying - you can't publish your fields till you filled all required fields. What's your thoughts on that?

<img width="650" alt="Screen Shot 2020-11-01 at 18 27 08" src="https://user-images.githubusercontent.com/1032526/97808508-fa3a3b80-1c6f-11eb-8e08-23aa45b3e1a7.png">

**Comment by aerugo** [comment]
@gustavlrsn - what does the "required" field actually do now? It doesn't seem to have any effect?

**Comment by aerugo** [comment]
Closed in issue clean-up.
