### ISSUE TITLE
Review text field needs to expand for large comments

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#138]
Guideline flag comments can be quite long. Writing long comments in the single-line text field is clunky. We should improve the UX to allow writing a longer comment more easily in the guideline review dialog.

**Comment by Powersource** [comment]
Took the liberty and pushed a fix straight to master https://github.com/Edgeryders-Participio/multi-dreams/commit/68ba74501373da205990c9f01974c9387ec879a8
