### ISSUE TITLE
Internationalization & ability to edit text per organization

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#141]
Ability to change some of the wording based on the organization.

I wonder since next already support some kind of i18n perhaps there is an easy way to acheive this.
For example - for Whtif instead of "Magic link sent" they want to display "Are you ready to start dreaming"?
There are many such cases.

**Comment by gustavlrsn** [comment]
Wondering if something like [Crowdin](https://crowdin.com) would support this usecase, of both providing internationalization and customization for different organisations. Their website says they have a free license for open source projects.

**Comment by aerugo** [comment]
I am making the call that for now: the Plato team will not implement this feature right now. It is very useful to be able to support internationalization and custom wording on the platform, and this is a feature that would fit perfectly for developers in the community to implement. However, we won't be able to fit the development of this feature into the releases of 2021 unless it is taken on by someone else.

**Comment by aerugo** [comment]
Closed in issue clean-up.
This will be implemented in 2022 but will open another more descriptive issue.
