### ISSUE TITLE
Add more info to user fields (+Upload profile image)

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#142]
- Ability for a user to upload (And replace) his profile image
- Ability for the organization to set User Fields (Both hidden and normal fields)
- Ability for a user to set "Hidden fields" that would only be available for the organization to see (Such as phone number or other fields)

At a later stage we would add a place for other users to see those fields (Such as when hovering over a user)

**Comment by gustavlrsn** [comment]
I think these make sense. One thing to note is that we're moving over users to Keycloak, so profile image stuff will probably happen there. As for organization user field values, we could put that in the OrgMember collection we will have in mongodb.

**Comment by rootux** [comment]
Oh I see.
Okay and is this managed in the same project or in another repository?

**Comment by gustavlrsn** [comment]
Same project, in this pull request: https://github.com/Edgeryders-Participio/multi-dreams/pull/135, hoping to merge within a week

**Comment by gustavlrsn** [comment]
Forgot, some of the models are imported from another repository: https://github.com/Edgeryders-Participio/plato-core (so that organizations and organization members are easier to share between dreams and realities)

**Comment by aerugo** [comment]
Closing this for now, as we should rather have a user profile set for Plato as a whole.
