### ISSUE TITLE
Allows custom fields to be For internal use only

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#143]
## What
Add another flag that would allow the organization to set custom fields as "Internal use only" - those fields would not be shown to the rest of the site visitors and might include private information such as phone numbers or other information

# Mocks
Organization admin view
<img width="921" alt="Screen Shot 2020-12-13 at 18 33 11" src="https://user-images.githubusercontent.com/1032526/102017802-b7d94380-3d71-11eb-9c9a-4e6a5c054255.png">

User editing a dream view
When a user then edit a field which is meant for internal use only - "👁 Internal only - visible to admins"
<img width="642" alt="Screen Shot 2020-12-13 at 18 36 32" src="https://user-images.githubusercontent.com/1032526/102017858-228a7f00-3d72-11eb-8a39-280f30863c6c.png">

## Things to notice
- Security wise - those fields should not be returned to all users but instead return only to specific users - The dream owner, event manager and organization root

**Comment by rootux** [comment]
@gustavlrsn What's your take on the UI is there a better way to display it for the users?

**Comment by gustavlrsn** [comment]
> @gustavlrsn What's your take on the UI is there a better way to display it for the users?

Nice. I think this is a good enough start. I'm thinking these fields should also be visible to guides (?), so a minor change would be to indicate that: "... visible to admins and guides"

**Comment by aerugo** [comment]
This is a feature that the Plato team won't implement right now, but we are open to PRs that implement this feature.
