### ISSUE TITLE
Support for predefined labels

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#144]
# What
Ability for an organization to set predefined labels per event - this is a list of tags such as "Burn night", "World peace", etc..
After defined by the `organization owner`
Those labels can then be set by the `dream owner` when editing the dream.
Those labels are also displayed on the dream page.

Integrate a select library (Such as React Select - https://react-select.com) - Allow multi selection of labels per dream.

As organization owner - allow to add new labels to choose from (Can be done using - https://react-select.com/home#creatable)

# Questions
- Do we want to support filtering / searching by those labels?
- **Missing designs**

**Comment by rootux** [comment]
@gustavlrsn Have any idea on where in the organization event settings this should exists?
Should we open a new tab under "Custom Fields" called "Labels"?
Some ideas I have 

<img width="718" alt="Screen Shot 2020-12-13 at 19 32 19" src="https://user-images.githubusercontent.com/1032526/102019077-ebb86700-3d79-11eb-97bc-f09a9ccbbbc2.png">

**Comment by gustavlrsn** [comment]
> @gustavlrsn Have any idea on where in the organization event settings this should exists?
> Should we open a new tab under "Custom Fields" called "Labels"?
> Some ideas I have
> 
> <img alt="Screen Shot 2020-12-13 at 19 32 19" width="718" src="https://user-images.githubusercontent.com/1032526/102019077-ebb86700-3d79-11eb-97bc-f09a9ccbbbc2.png">

I'd be fine with this solution!

**Comment by aerugo** [comment]
This is made redundant by #157
