### ISSUE TITLE
Ability to set the website background & event cards

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#145]
1. Add ability for an orgnization to set a background for the website
2. Add ability to set an event card background (For the organization view)
3. Make sure that the website background is also the email background[?]

Inspiration
![Screen Shot 2020-11-10 at 10 08 20](https://user-images.githubusercontent.com/1032526/102249232-ceff6900-3f0a-11eb-8bb5-7700dbfbd2d1.jpg)
![Screen Shot 2020-11-10 at 10 02 08 copy](https://user-images.githubusercontent.com/1032526/102249237-d0c92c80-3f0a-11eb-8091-638bb291d8c1.jpg)
![Screen Shot 2020-11-10 at 10 16 24 copy](https://user-images.githubusercontent.com/1032526/102249242-d1fa5980-3f0a-11eb-92ea-4e79f3948663.jpg)

**Comment by aerugo** [comment]
This is something we want before the summer release.

**Comment by rootux** [comment]
We are looking into that - would update.
When is the Summer Release planned?

**Comment by aerugo** [comment]
Our funding ends on July 1st, so before then we want to have a release ready that is mature enough for people to understand and use without prior experience.

**Comment by aerugo** [comment]
Closed in issue clean-up.
