### ISSUE TITLE
Create org throws back to localhost

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#147]
On org creation, the user is thrown to the localhost URL.

Steps to reproduce:

- Create an org on https://dreams.wtf/organizations/create
- Get thrown to http://yoursubdomain.localhost:3000/

**Comment by aerugo** [comment]
Ping @gustavlrsn - this one is a priority. New users get very confused about creating their orgs and then getting redirected to a localhost URL.

**Comment by gustavlrsn** [comment]
Fixed in e50d71227382a199c7c1cf346c5578488ce116b0.
