### ISSUE TITLE
no "invite members" option visible

### ISSUE THREAD

**Issue by hesslau** [Edgeryders-Participio/multi-dreams#150]
I'm admin of https://kiezburn.dreams.wtf/kiez-burn-2021/members and set the registration policy to "invite only" – but how do I invite someone? I can't find anything in the UI for this

**Comment by gustavlrsn** [comment]
Since switching to Keycloak for auth/user management we havn't re-implemented the invite feature yet. An option could be to use "Request to join" as registration policy until it is fixed.

**Comment by aerugo** [comment]
When do we expect to have the invite feature working again? Had a question about that today. Ping @gustavlrsn

**Comment by aerugo** [comment]
@hesslau - an MVP of this is ready now. 
You can now invite to the org and to the event.
