### ISSUE TITLE
Discourse integration improvements

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#151]
The mvp of the discourse integration is live. Here we can add more issues related to it as we test it out.

- [x] ability to configure which user to post new threads from, right now it is "system"
- [x] ability per event to choose which category to post new dreams to
- [x] edit comments in dreams
  - discourse API only seems to return "cooked" comments (i.e. html and not raw markdown) when asking for an entire thread, so requires an extra step of fetching the markdown of specific comment to be able to edit
- [x] keep title in sync
- [x] add dream information (images, description etc) to discourse post
- [x] link to discourse thread above comments in Dreams
- [x] don't allow me to try to submit comments with less than 20 chars (discourse min limit)
- [x] all dreams are now instantly posted to discourse, regardless whether they are marked as Published or not..

**Comment by aerugo** [comment]
>  don't allow me to try to submit comments with less than 20 chars (discourse min limit)

This is actually configured on the discourse instance, so low priority.

>  add dream information (images, description etc) to discourse post

The way this should work is that the images and fields from the dream get pieced together into the first post of the topic, and that topic is then updated anytime the dream is updated.

**Comment by aerugo** [comment]
@gdpelican - let us know what you will start working on.

**Comment by gdpelican** [comment]
@gustavlrsn I've been struggling a bit today with setting up the new Discourse integration on my local; from what I can tell from reading the source `ui/.env` wants to have two variables populated, a public and private key pair generated via forge. I've done something like this to generate a pair:

```
const forge = require('node-forge')

pair = forge.pki.rsa.generateKeyPair({ bits: 2048, e: 0x10001 })
publicKey = forge.pki.rsa.setPublicKey(pair.privateKey.n, pair.privateKey.e)

private = forge.pki.privateKeyToPem(pair.privateKey)
public = forge.pki.publicKeyToPem(publicKey)
```
then exporting `private` to `PRIVATE_TOKEN_KEY` and `public` to `NEXT_PUBLIC_TOKEN_KEY`.

I've been able to get through the `connect/discourse` route and granted access on the Discourse side, but the `ui/pages/connect-discourse` script always chokes on decrypting the response from Discourse.

From what I can tell, I think the trouble here is some trickiness around getting dotenv to store and parse these values correctly, which I haven't quite been able to get the alchemy correct on. Currently it's looking like:
```
NEXT_PUBLIC_TOKEN_KEY="-----BEGIN PUBLIC KEY-----\nMIIB...."
PRIVATE_TOKEN_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIE...."
```
but I've tried lots of iterations, including line breaks in the .env file, `\r\n`, etc etc; I've received various errors messages here including
```
Uncaught Error: Too few bytes to read ASN.1 value.
Uncaught Error: Invalid PEM formatted message.
Uncaught Error: Too few bytes to parse DER.
```

Some docs or guidance on this would be super helpful!

I reckon once the integration is up and running I'll start with the syncing and user configuration tasks, which seem like low hanging fruit.

**Comment by gustavlrsn** [comment]
@gdpelican your way of generating them and how they look seem very correct.. Are they located in `ui/.env.local`?  `MONGO_URL` should also be in the same file for the Discourse integration to work. Adding some placeholders for these to `ui/env.local.default` now

**Comment by gustavlrsn** [comment]
Generated and added `PRIVATE_TOKEN_KEY` and `NEXT_PUBLIC_TOKEN_KEY` in `ui/.env.development` instead, that can be used for development so that you don't need to generate them yourself.

**Comment by aerugo** [comment]
How are things going @gdpelican ?

**Comment by gdpelican** [comment]
I've gotten the Discourse integration going last week and opened [this PR](https://github.com/Edgeryders-Participio/multi-dreams/pull/158) to start on an interface between multi-dreams and an arbitrary platform.

Today I'll pull out the existing Discourse calls into that interface, and have a look at a few improvements in that area as well.

**Comment by aerugo** [comment]
Getting the features above to work for Discourse should be our main priority, with additional platform support coming later. Reason for this is that our funding explicitly states that we are developing these integrations for Discourse, and that’s what we need to focus on until June. However, I do see the benefit of doing some groundwork to support other platforms too, like Loomio - before developing these features, it just can’t take too long.

How much time do you estimate it would take to build the more general interfacing layer? If it’s less than two weeks, go ahead. If it’s more, we need check off some of the other items on the list first as those have more bearing on our funded deliverables.

**Comment by aerugo** [comment]
Or perhaps you’re planning to make progress on both the features and the general integration in the new pub/sub module?

**Comment by gdpelican** [comment]
Yep, both will happen at the same time; I'm planning on getting some of these checked off the list today (the pub/sub approach will make this an easier time both now and in the future I believe)

**Comment by aerugo** [comment]
> the pub/sub approach will make this an easier time both now and in the future I believe

Agreed!

That's great then. :)

**Comment by gdpelican** [comment]
Alright, finally got some tangible progress to show here, on the `event-hub` branch (I've marked the completed functionality on the checklist above)

Some questions:
- When we say 'configure' the default user, do we mean in the interface, or via .env variables?
- For the category chooser, I was thinking of putting it in the interface under a new 'Discourse' section in the Event Settings; does that seem right?
<img width="231" alt="Captura de Pantalla 2021-03-16 a la(s) 1 04 23 a  m" src="https://user-images.githubusercontent.com/750477/111150972-ac591b00-85f3-11eb-8167-1348c2445d75.png">

- There's some hints in the code that we're looking for Discourse to replace the mongodb backend when the integration is enabled; this is a pretty scary requirement given all of the things that can happen to a Discourse comment (edited, hidden, reverted, moderated, flagged temporarily, withdrawn, marked as spam, deleted by staff, etc etc etc). It's also fairly odd to be combining existing non-discourse comments with new Discourse ones, and having to fetch and display them both from 2 data sources. I think to start at least, this can get off the ground much more quickly if we store all comments in mongodb on the Dreams side, which will act as a publisher to Discourse as a side effect; we can explore what a two-way integration might look like further down the road.
 
I've still got a bug or two to shake out in that branch, but should be good for testing fairly soon.

**Comment by aerugo** [comment]
> When we say 'configure' the default user, do we mean in the interface, or via .env variables?

I think in the interface. It seem like the easiest way to do this is to have a field in the admin interface that allows you to input the API key for a bot-user that you have created on Discourse.

> For the category chooser, I was thinking of putting it in the interface under a new 'Discourse' section

Good enough for now, I think. @gustavlrsn?

> There's some hints in the code that we're looking for Discourse to replace the mongodb backend when the integration is enabled

I actually think this is already the case, right @gustavlrsn? And it seems to work pretty well. For the [Blivande org](https://dreams.blivande.com/), the [Blivande Discourse](https://forum.blivande.com/c/plato/blivande-dreams/48) has been connected. If you look [at this Dream](https://dreams.blivande.com/frihamnstorget-2020/5f02dfdff290410008d57032), that is actually loading comments live from [this Discourse topic](https://forum.blivande.com/t/jakob-test/2042). 

What we want to achieve here is that if a community runs a forum, all conversations about dreams end up on that forum. In my experience, it is very important that the conversation and decision making of a community does not get fragmented across platforms. At the Borderland, we had a one-way flow - displaying comments from an automatically created Loomio topic on the old Ruby on Rails Dreams platform. Users couldn't comment through the Dreams platform but were instead directed to the Loomio thread. [See this example](https://talk.theborderland.se/s/JreK7Xox).

As I understand it, a dream never displays comments from two sources. If the Discourse integration is enabled for an org, then all comments go to Discourse. If the user does not have a Discourse user, one is created for them - actually using the same plugin that you developed for the Edgeryders forms.

> all of the things that can happen to a Discourse comment (edited, hidden, reverted, moderated, flagged temporarily, withdrawn, marked as spam, deleted by staff, etc etc etc).

From the point of view of Plato Ideas, it should be pretty simple simple: If the comment is readable by the user that is logged in, it is shown. For users who are not logged in, only publicly visible comments are shown. I think this is already the case, right @gustavlrsn ?

**Comment by gustavlrsn** [comment]
> > For the category chooser, I was thinking of putting it in the interface under a new 'Discourse' section
> 
> Good enough for now, I think. @gustavlrsn?
> 
Sounds good to me!

> > There's some hints in the code that we're looking for Discourse to replace the mongodb backend when the integration is enabled
> 
> I actually think this is already the case, right @gustavlrsn? 

Yep.

> As I understand it, a dream never displays comments from two sources. If the Discourse integration is enabled for an org, then all comments go to Discourse. If the user does not have a Discourse user, one is created for them - actually using the same plugin that you developed for the Edgeryders forms.

A dream can actually display from two sources, if there was comments added to the dream prior to the discourse integration was set up, comments from both MongoDB and Discourse will be displayed. The idea is to provide a way to preserve those comments without having to do a migration.

> > all of the things that can happen to a Discourse comment (edited, hidden, reverted, moderated, flagged temporarily, withdrawn, marked as spam, deleted by staff, etc etc etc).
> 
> From the point of view of Plato Ideas, it should be pretty simple: If the comment is readable by the user that is logged in, it is shown. For users who are not logged in, only publicly visible comments are shown. I think this is already the case, right @gustavlrsn ?

We are currently sending along the general api key when fetching comments. I'm testing the API now and Discourse doesn't require any api key for public content so we should switch so that we're not sending any api key when user is not logged in and send the user api key (if that exists) when logged in. 

Might be that we're currently displaying some hidden or flagged comments right now? Deleted posts are not displayed though, I've tested that.

**Comment by gdpelican** [comment]
>  At the Borderland, we had a one-way flow - displaying comments from an automatically created Loomio topic on the old Ruby on Rails Dreams platform. Users couldn't comment through the Dreams platform but were instead directed to the Loomio thread. See this example.

Alright, cool. In that case, if the flow wants to be one-way from Discourse (or others) to Dreams, can we disable the ability to comment on Dreams when Discourse is integrated? Maybe we replace the 'comment' button with a link to the thread in question, so people can comment there [I put in a link to the Discourse thread already above the comment section, so that should be a quick and easy change]

**Comment by aerugo** [comment]
>  In that case, if the flow wants to be one-way from Discourse (or others) to Dreams, can we disable the ability to comment on Dreams when Discourse is integrated?

No need, because the integration that @gustavlrsn has built allows you to leave a comment on Discourse through the Dreams interface. Try it out by commenting on this dream: https://dreams.blivande.com/frihamnstorget-2020/5f02dfdff290410008d57032

**Comment by aerugo** [comment]
So, to clarify:
In the old version, the flow was indeed one way. Now, Plato Ideas will post to Discourse for you.

**Comment by gdpelican** [comment]
Alright, I've made some progress here to the point that it's ready to show; here's a demo of the changes listed above:
https://www.loom.com/share/d28f404c61564eb498fc4a1eaab43794

Let me know how that's looking, what some good next steps feel like, and if I've broken anything? 😅

**Comment by gustavlrsn** [comment]
Nice! Looks great overall, found some issues when testing:

- When adding a comment it is not added in the UI until a page refresh 
  - Previously the resolver for the addComment mutation was awaiting the discourse api call before resolving so you would be sure to get back the dream with the new comment 
  - I saw in your demo that this seems to work on your end, but I'm guessing that is due to the slowness of the mutation, i.e. the discourse subscriber has enough time to actually post the comment before the mutation is fully resolved (Sidenote: maybe the slowness is due to a lot of roundtrips between your local dev server and the keycloak server located in Europe, when it resolves Users  from Keycloak for instance)
  - Would it be possible to somehow await the discourse api call before returning/resolving the `addComment` mutation? 
- Adding a comment before the dream is published throws an error
  - Wondering what to do with these now since dreams are not posted to discourse until they are published (which makes a lot of sense btw). 
  - Should these be posted first to mongo and then migrated to discourse when the dream is published? 
  - Or maybe another way is to post the thread with some hidden visibility setting (if that is possible on Discourse?)
- All thrown errors from the discourse subscriber crashes the app, maybe we need a try/catch block somewhere to prevent the entire app from crashing when there is an error

I also pushed a small fix to the PR, to use the current organizations discourse url instead of the env variable  to create the `discourseTopicUrl`.

**Comment by aerugo** [comment]
Great job @gdpelican! Continue by fixing the stuff that @gustavlrsn has brought up. 

Some questions: 

- Does the Discourse post no sync 1-to-1 with the Dream? If the Dream is updated, the Discourse post content is edited and replaced by a newly generated version?

- I'm unsure if the Discourse topic should be posted by the user that presses "publish".  It might create some confusion among users. For example, consider the following chain of events: 
  1. I create a dream that generates a Discourse topic.
  2. Not understanding the direction of the data-flow, I edit the discourse post with new info. Now the Dream and the topic are not in sync.
  3. I add a picture to my Dream on Plato. A new version of the generated topic now replaces the old version, and the edits I made on Discourse are discarded. 

This is a pretty confusing UX. To avoid this, we should probably have all topics be posted by a bot user, to make it clear that the post is updated by updating the Dream on Plato. To clarify this further, each topic posted from Plato should probably start with a disclaimer that links back to the Dream and states that the topic can be updated by updating the Dream.

**Comment by gdpelican** [comment]
- Yep, the Discourse post syncs with the dream with edits to Summary, Budget, Description, Title, and images (and will be trivial to sync with any future fields / things I've missed)
- I've updated this to ensure the dream itself is posted by the system user now

> Adding a comment before the dream is published throws an error
Hmm this is an interesting one. In an ideal world, posting to Discourse is a side effect and doesn't slow down the resolver at all, and instead once the comment has resolved it notifies a GraphQL subscription so the client gets live updated.

https://www.apollographql.com/docs/react/data/subscriptions/

I believe having a subscription has the added benefit of allowing people to post comments on Discourse which will also show up in the Dreams interface automagically.

However, it doesn't seem like the fastest way to get this up and going, so maybe we just want to chuck an `await` in there for now?

> Adding a comment before the dream is published throws an error
Hmm okay so there is some code in there (which I _think_ works?) which says, when creating a Dream on Discourse, then emit a series of `create-comment` events for all local comments on that dream. So I think we should be able to get away with some logic like
- If a comment is created before the dream is published, store it in MongoDB
- When a dream is published, post it to discourse, then post each of the comments to Discourse
One question here is, does it make sense / have any benefit to remove comments from MongoDB once a dream is posted to Discourse?

**Comment by aerugo** [comment]
@gustavlrsn, are we ready to merge #158  or do we need something else clarified or changed?

**Comment by aerugo** [comment]
We are already seeing the fruits of this work pay off: 
https://dreams.blivande.com/frihamnstorget-development/606b09de386d4a002c6e96b8

What becomes evident here is that when linked to an active other forum, the Dreams platform becomes a lot more interactive and generative.

**Comment by gustavlrsn** [comment]
> @gustavlrsn, are we ready to merge #158 or do we need something else clarified or changed?

Added some smaller fixes and [written down some remaining issues in the PR](https://github.com/Edgeryders-Participio/multi-dreams/pull/158#issuecomment-816302051).
