### ISSUE TITLE
Improve mobile menu

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#154]
From [user test](https://forum.blivande.com/t/user-test-1/2030):
> PRIO The menu is not very clear, it is unclear what is the menu and what is not. It should probably pop out somehow?
PRIO Menu closing “x” need to follow scroll.
PRIO Menu should disappear after a menu item is pressed. Now it stays after pressing e.g. new dream.

**Comment by aerugo** [comment]
Closed in issue clean-up.
