### ISSUE TITLE
Tagging feature for dreams

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/multi-dreams#157]
Back in the old days of the Borderland dreams platform, there was a tagging feature for dreams. I think it would be useful to bring that back in some reworked capacity. Basically:

### Functionality
* A User should be able to add one or more tags to their dream. 
* A Guide or Admin should be able to add one or more tags to all dreams. 
* An admin should be able to decide if creating tags can be done by users or only by admins. 
* Tags are defined on event level. 
* All tags on a dream are displayed on the dream when viewed in the event.

### Additionally
* I also think it would be nice if the first tag altered something about the appearance of the dream, maybe a colored border defined by the tag color?
* Back in the BL version anyone could define tags for any dream. This was fun, but is probably not useful for the majority of events. However, it could be nice to keep it as a function. 

### Reasons for this
* Almost all events have different categories for dreams. At Borderland we have infrastructural dreams, permanent dreams, dreams that are more like performances, and dreams that are more like spaces. These definitions are of course never clear cut, but it's useful to be able to sort dreams.
* There is currently a couple of organisations that will use Plato Ideas as an idea-generating tool. The way they will do this is through workshops where people define visions for a place, and then workshops that turn visions into prototypes, and then workshops that turn prototypes into finalized project proposals. There will be different people engaged in the ideas throughout all these workshops, and the workshops will run asynchronously. For this setup to work they need to be able to filter ideas depending on if it's a vision, a prototype, or a proposal. Otherwise, they need to set up 3 events for this, which is not an ideal setup since then ideas need to be copied from one to another when they go to the next stage. Tagging would solve this.

**Comment by rootux** [comment]
That's great.
This one is more ellaborate then #144
 https://github.com/Edgeryders-Participio/multi-dreams/issues/144

**Comment by aerugo** [comment]
The first version is now live. However, there is still some work to do.

[ ] Collection tags should be shown on the front page

One idea for how to do this could be how Kickstarter does it:

![Screenshot 2021-05-18 at 20 54 33](https://user-images.githubusercontent.com/7785081/118708220-bf6ab000-b81b-11eb-89b4-41b6ec7b406c.png)

[ ] Already applied dream tags in the collection should be easily available to apply to new dreams

We need to figure out a good UI for this.

[ ] It should be customizable if new tags can be created by anyone or just by admins.
