### ISSUE TITLE
Can't reach bottom of General Event settings on a 1080p screen

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#164]
Can't scroll there

**Comment by Powersource** [comment]
Can't reproduce this atm. Can you @aerugo ?

**Comment by aerugo** [comment]
No, I can't. Leave this in that case. We can close it for now.

**Comment by rootux** [comment]
Yeah. There is an issue with positioning in the settings screen.
I can reproduce it here on my mac and firefox.

**Comment by aerugo** [comment]
Could you screen record and upload the video @rootux ?

**Comment by aerugo** [comment]
Closed in issue clean-up.

**Comment by aerugo** [comment]
This seems as if it is fixed?

**Comment by Powersource** [comment]
think it might have gotten fixed when we switched away from the modal
