### ISSUE TITLE
Improve granting/budget settings

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#166]
Current limitations

- can't set dream submission closes after granting starts
- need to set explicit total budget
- unclear UX of what needs to be set first etc

**Comment by aerugo** [comment]
Also related to #69.

**Comment by aerugo** [comment]
We need to make the granting/budget work for permanent communities as well as for events, for example through implementing #171

**Comment by aerugo** [comment]
Closed by #196 196
