### ISSUE TITLE
Display all images on dreams page

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#17]
Right now there is only a cover photo (first image in the array of images on a dream).

It would be great to display all photos on the dream page, something like this, and have them be able to be opened larger as an overlay, or simply in another tab:
<img width="587" alt="Skärmavbild 2020-01-25 kl  13 30 18" src="https://user-images.githubusercontent.com/1552194/73121114-ec37eb80-3f76-11ea-90b9-58773bd8d270.png">

**Comment by konstilackner** [comment]
Working on it branch: 17-display-images

**Comment by danielres** [comment]
done
