### ISSUE TITLE
Add onboarding todo-list

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#172]
Will be placed next to the grid of events

* [ ] Only show for org admins
* [ ] Add a tiny skip button that removes it (with confirmation)

![image](https://user-images.githubusercontent.com/1427063/112486056-d5a84280-8d7b-11eb-8550-9ebfbdb46eca.png)

**Comment by rootux** [comment]
Great.
Does #5 adding integrations like discourse really needed to get people
engaged?

Perhaps there are other things such as invite first members, add tags, get
people to comment.

P.S Love the design

**Comment by Powersource** [comment]
No it's not necessary, nr 3 isn't needed either unless you want to use Realities, but we've argued this list is to get the user to start exploring what's possible with the app(s), not necessarily stuff you have to do. But yeah it's definitely up for debate (even if I'll prob aim for these ones to start with just to have something).

And the design is by @gustavlrsn , the screenshot is from our new Figma :)
