### ISSUE TITLE
Can't create an event with the same slug as an event in another org

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#173]
Getting this in an alert `GraphQL error: E11000 duplicate key error collection: test.events index: slug_1 dup key: { slug: "frihamnstorget-2020" }` when I go into my mostly empty test org and try to create an event with the slug "frihamnstorget-2020" (already exists as an event in blivande)

**Comment by gustavlrsn** [comment]
There was a unique index on `slug` in the production db that I removed now, in addition to the compound unique index on `slug` and `organizationId` that should be there. Closing.
