### ISSUE TITLE
About greeting box has overlapping text on mobile

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#174]
![8EFBBF5D-32B8-498E-BAD6-75BDA7CB1B52_1_102_o](https://user-images.githubusercontent.com/7785081/112537477-06ee3600-8daf-11eb-90a1-052ea0b5dc70.jpeg)

This sometimes happens on mobile, or at least on iOS.

**Comment by Powersource** [comment]
I think I saw this on pc as well. It was overlapping until i pressed the "V" to expand the text.
