### ISSUE TITLE
Loomio integration

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#179]
Allow connecting Dreams to either Loomio or Discourse.

**Comment by aerugo** [comment]
@gdpelican, based on your experience so far, how feasible to do think it will be to offer orgs to integrate with Loomio as an alternative to Discourse?

**Comment by gdpelican** [comment]
From Dreams' end, it should be very easy.

From Loomio's end, we'll need to do some tiptoeing to get the API up to scratch for this, which means a (hopefully small) plugin which folks could install to allow for this (I'm also wondering if I could get away with contributing a small feature to the Loomio codebase, per [this suggestion](https://github.com/loomio/loomio/pull/5885#issuecomment-552308058) to allow us to run something in the console to generate an api key and use that.)

I can do some investigation into this once the Discourse integration is up and running properly, but given how flexible the Loomio system is we should be able to find some path forward on this.

**Comment by aerugo** [comment]
Great. Once the integration is up, perhaps we should schedule a call with Rob? I've been meaning to catch up with him anyway.

**Comment by aerugo** [comment]
Not doing this for the time being.
