### ISSUE TITLE
Add ToS and GDPR agreements

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#180]
We need to have ToS and GDPR agreements on registration. @skoteskote is going to generate legal texts based on a service he has used for another project. We will then implement the same agreements for all apps on Plato in the sign-up process.

**Comment by rootux** [comment]
I believe WHT-IF has started this operation. I'll check.

**Comment by Powersource** [comment]
https://github.com/Edgeryders-Participio/multi-dreams/issues/207

https://github.com/Edgeryders-Participio/multi-dreams/issues/208
