### ISSUE TITLE
Ability to set logo size

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#184]
How about in the org settings ability to set logo size with S M L

This is the current state small - 
<img width="1021" alt="Screen Shot 2021-03-28 at 16 36 18" src="https://user-images.githubusercontent.com/1032526/112754256-ea870f00-8fe3-11eb-8223-4d99d80cca60.png">

This can be large
<img width="1017" alt="Screen Shot 2021-03-28 at 16 37 14" src="https://user-images.githubusercontent.com/1032526/112754262-f541a400-8fe3-11eb-8abc-b811d00f3251.png">

Just checking if I'll work on it that it would get merged @aerugo

**Comment by aerugo** [comment]
Would this mean that the top bar would be wider too? Not sure if it's worth the trade-off in that case.

<img width="2799" alt="Screenshot 2021-03-28 at 15 57 30" src="https://user-images.githubusercontent.com/7785081/112754862-68481c00-8fde-11eb-87b7-b4f16b52c734.png">

Or are you only referring to the org settings screen?

**Comment by aerugo** [comment]
I think we should pick a size that fits most cases and stick with that. Adding customization menus for this seems a little overkill. We also need to take care to avoid this:

![](https://imgs.xkcd.com/comics/manage_your_preferences_2x.png)

**Comment by rootux** [comment]
@aerugo I was referring to the whole experience.
Yes. It would make the top bar bigger.
Okay. let's wait to see if other organizations also shares this need

**Comment by rootux** [comment]
Closing for now
