### ISSUE TITLE
Make budget and funding optional in an event/collection 

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#187]
We are seeing an increasing amount of use cases where the funding is not really relevant. For example, when Dreams is used to accept [applications for Galleri Frihamnstorget](https://dreams.blivande.com/gallery). In these cases, it would be preferable to be able to remove the budget item from the form as it could otherwise be misunderstood to mean that accepted projects would be funded according to their budgets.

**Comment by rootux** [comment]
Perhaps an easy way for this to happen is at event creation the description
and budget fields would be added automatically as custom fields.

We can add a new type called budget that would be assigned to the budget
field.

That way an event owner can choose wether to include budget and description
and wether they are required.

**Comment by rootux** [comment]
Or perhaps I'm overthinking it and a simple disable budget checkbox might
do 😊

**Comment by aerugo** [comment]
Closed in issue clean-up.
