### ISSUE TITLE
Allow creating a Dream without an account

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#190]
For citizen-engagement project, the barrier to entry must be really low. In these cases, it would be good to allow people to first create their Dream, and then immediately get asked to create an account in the same flow in order to save the Dream. Enabling this should be a Collection setting.

**Comment by rootux** [comment]
Great. What do you mean by "Collection" setting?

**Comment by aerugo** [comment]
Sorry, this is me prematurely applying terminology that hasn't been settled yet: https://forum.blivande.com/t/plato-terminology/1188/9

We've realized that what we currently call "event" is actually not being used as an event by many users, but rather as a thematic collection of proposals related to a certain thing. 

See these examples: 

https://dreams.blivande.com/blivande-academy

https://dreams.blivande.com/gallery

https://moos.dreams.wtf/house-investments

https://dreams.theborderland.se/dream-generator
