### ISSUE TITLE
Share to other social media platforms

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/multi-dreams#192]
Allow for a user to share a dream to different social media platforms.

It should be dead simple to share a dream to other social media platforms. I hate the ugly little share buttons, so maybe they can be optional?

Obv it's easy to just share the link to the dream. But 1. some users don't know this, and 2. people forget about it and the share buttons remind them.

**Reason:**
That's how we get traffic to the platform when it's used for contexts where there is no clearly defined community using it, like e.g. an open citizen initiative process. People who don't use dreams/realities/discord in their daily life will log on two times and then forget about it. This also brings in new users for open processes.

**Example:**
To continue using the example of Simrishamnsförslaget; they explicitly urge participants to share their suggestions on facebook, this is how they can get a decent participation even if it's a one-way one-purpose platform. The local fb-groups for the little villages around here are teeming with people posting links to their suggestions on Simrishamnsförslaget.

**Comment by aerugo** [comment]
Do people really use share buttons? People don't just copy-paste links?
Do we have any research on this? I have always had a feeling that these
sharebuttons are just being added because they are "supposed to be there".

**Comment by rootux** [comment]
I agree that the minimum thing here would be to make sure we set the
og:image og:title og:description so that when copy and pasting into social
network - it would look good

https://css-tricks.com/essential-meta-tags-social-media/

**Comment by aerugo** [comment]
Closed in issue clean-up.
