### ISSUE TITLE
Access Realities API through Dreams API

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#195]
We are preparing to build integrations to access Realties data through Dreams. 
One solution might be to implement schema stitching to avoid having two Apollo Clients. 
Another possible solution is Apollo federation.

**Comment by Powersource** [comment]
I think I'm gonna go with using the [`client` argument](https://www.apollographql.com/docs/react/data/queries/#client) on useQuery/useMutation, it's the simplest solution that works for now, without feeling too odd.
