### ISSUE TITLE
Require the user to approve the ToS and privacy policy on sign up

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#207]
We need to implement approving our TOS.

https://www.iubenda.com/terms-and-conditions/58637640

**Comment by skoteskote** [comment]
There need to be a check box for the user to approve ToS when a user signs up, and we need to register date and time of approval + version of the document in our user database.

**Comment by skoteskote** [comment]
The user should also approve the privacy policy here https://www.iubenda.com/privacy-policy/58637640
Easiest will be two separate link to Terms of Service and Privacy Policy, and then one check box asking if the user approves these.

**Comment by Powersource** [comment]
![image](https://user-images.githubusercontent.com/1427063/116404783-43d69e00-a82f-11eb-82dd-d6679492d5e5.png)

**Comment by Powersource** [comment]
Keycloak seems to save the timestamp of when you accepted the terms 
![image](https://user-images.githubusercontent.com/1427063/116405050-84361c00-a82f-11eb-91a6-ac90adc8e978.png)

**Comment by skoteskote** [comment]
Perfect! Where is the timestamp recorded? In our db somewhere?

**Comment by Powersource** [comment]
Yes, specifically in keycloak's db. It should be requiring it from new users now, but not existing ones, I'm working on that part.

**Comment by Powersource** [comment]
Note for future self: in [keycloak 13](https://keycloak.discourse.group/t/condition-user-attribute/7705) (unreleased) we might be able to create a custom login flow that always requires the ToS using [`Condition - User Attribute`](https://www.keycloak.org/docs/latest/server_admin/#conditions-in-conditional-flows)

**Comment by Powersource** [comment]
All users should now be asked on next login to accept the ToS and privacy policy.
