### ISSUE TITLE
Not able to see entire member list

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#209]
When you are looking at the member list, it is not big enough to show all of the options that you have available.   I am on a big screen, there is tons of space to the left and the right of the menu component.

It is not a big thing but it is super annoying. Could you change it so that it will show the entire component when there is space to do so, and so that the scrollbar at the bottom is always visible please?

![example_for_dreams](https://user-images.githubusercontent.com/1898086/115245743-8e686400-a125-11eb-8f4d-7c0dae61ee26.PNG)
![Example_for_dreams2](https://user-images.githubusercontent.com/1898086/115245870-a93ad880-a125-11eb-84c0-54c79b427c1c.PNG)

**Comment by aerugo** [comment]
I think this should be a pretty fast fix - @Powersource, could you have a look?

**Comment by aerugo** [comment]
I think all items should fit on that table. It's important that it is reasonably consistent between screen sizes. 

Perhaps we should:

1) Make long emails line-break.
2) Concatenate long bios to avoid them making the list items crazy big.

What do you think @gustavlrsn?

**Comment by Powersource** [comment]
@aerugo did you mean truncate instead of concatenate? In that case I don't know if you would have any way of reading the whole bio for people if it's too long, but maybe that's not a big problem for now

**Comment by aerugo** [comment]
Yes, I meant truncate, just a slip.

**Comment by DiarmaidEverycs** [comment]
Very nice :)

**Comment by Powersource** [comment]
Seems like Gustav fixed this

**Comment by Powersource** [comment]
ah seems it was fixed even before this issue was opened, just in a separate branch :P https://github.com/Edgeryders-Participio/multi-dreams/pull/196/commits/2a45db0e3139455afac20503238128d33c989bf1
