### ISSUE TITLE
Comment pagination and sorting

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#211]
We should paginate comments and allow sorting by most recent on top or on the bottom.

This would probably also fix #210

**Comment by aerugo** [comment]
@gdpelican, could you have a look at this once we've finalized #158?

**Comment by aerugo** [comment]
@gdpelican we talked about this in our meeting today. We should implement it so that the last page of comments is the one that is loaded first, and that there is an option to "load more comments above" or similar.

**Comment by aerugo** [comment]
@gdpelican - have you had a chance to look at this yet?

**Comment by gdpelican** [comment]
I have gotten a start, but nothing to show just yet. I have Tuesday this
week blocked out to get this to presentable :)

**Comment by gdpelican** [comment]
Alright, this one is good for a look _with the exception_ of deleting not updating properly; I have time tomorrow blocked off for that one. (Lots and lots of cache invalidation, haha)

**Comment by aerugo** [comment]
Done. Closed in issue clean-up.
