### ISSUE TITLE
Keep to-do list on screen during org-creation flow

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/multi-dreams#212]
Keep to-do list on screen during org creation flow. 

The new org creation to-do flow is great! It is a bit confusing though that after pressing eg "invite members", the to-do list is gone and there is no clear way to navigate back to it. Ideally it would stay on the side when the "invite members" screen shows, and same for creating events etc.

**Comment by aerugo** [comment]
Yup! Let’s separate this into two issues (keep todo visible on other
screens, and show feedback after finishing todo) and define them a little
more clearly so that they’re easier to address.
