### ISSUE TITLE
Fix issue with apollo client/cache (currentOrg and currentOrgMember goes null on client side transition)

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#217]
The `TOP_LEVEL_QUERY` in `ui/pages/_app.js` is supposed to fetch the basics needed in many places, such as `currentOrgMember` and `currentOrg`, but since switching to apollo client 3 there seems to be some issues with this cache when doing a client side transition these values will go null.

Might need to look at the apollo client setup.

**Comment by aerugo** [comment]
What is the effect of this issue for the end users?

**Comment by gustavlrsn** [comment]
When going to the root/organization home, the page will display the landing page until currentOrg is resolved (load https://dreams.blivande.com/frihamnstorget-2020 and then click the org logo), and the profile dropdown will switch to Login/Signup button until currentOrgMember is resolved

**Comment by aerugo** [comment]
Closed in issue clean-up.
Apollo is being replaced.
