### ISSUE TITLE
Granting feature tweaks

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#222]
- [x] Event display cards should indicate if a dream is open for granting. Dreams that are not approved for granting should not have their progress bar displaying. 
- [x] Granting currently does not work without setting the "Granting opens" date. When it is set, granting works. The expected behavior is that if nothing is set in "Granting opens" then granting is always possible. 
- [x] It is not possible to set the "Granting opens" field back to empty/not set.
- [x] When funding is canceled and money is returned, the dream should be automatically set to not approved for granting.
- [x] There should be a way to re-open a dream for granting that has once been canceled. If an admin approves a cancelled dream for granting again, it should be possible to give to that dream again.

**Comment by gustavlrsn** [comment]
Fixed and deployed these to production

**Comment by aerugo** [comment]
@gustavlrsn - looks like progress bar is now never visible on the dream card, even after it has been approved?

**Comment by aerugo** [comment]
There was also a separate issue with the "granting opens", which is that it is not possible to set the "Granting opens" field back to empty/not set. I now separated that out to another item in the issue to be resolved. This should also be resolved for "Dream creation closes" and "Granting closes".

**Comment by gustavlrsn** [comment]
> @gustavlrsn - looks like progress bar is now never visible on the dream card, even after it has been approved?

Ops, was missing picking out the approved field in the dreams list query.

**Comment by gustavlrsn** [comment]
> There was also a separate issue with the "granting opens", which is that it is not possible to set the "Granting opens" field back to empty/not set. I now separated that out to another item in the issue to be resolved. This should also be resolved for "Dream creation closes" and "Granting closes".

Added the ability to clear all these dates.
