### ISSUE TITLE
Unable to use Facebook to authenticate

### ISSUE THREAD

**Issue by DiarmaidEverycs** [Edgeryders-Participio/multi-dreams#227]
I tried to log into Dreams using Facebook, and got an error that the application was still in development mode.

![image](https://user-images.githubusercontent.com/38034266/115863676-160be680-a436-11eb-8865-6b85ce8d1f2c.png)

**Comment by aerugo** [comment]
This is on our todo in the next couple of weeks, along with adding Google.

**Comment by Powersource** [comment]
Tracking this here instead https://github.com/Edgeryders-Participio/plato-core/issues/7
