### ISSUE TITLE
Granting does not work when stretch goals are enabled if max budget not set

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#233]
Steps to reproduce:

 - Enable stretch goals
 - Do not add a max budget
 - Try to give a grant

**Comment by gustavlrsn** [comment]
@aerugo I can't reproduce this bug, does it happen somewhere in production?

**Comment by aerugo** [comment]
Weirdly enough, no, not anymore. Perhaps it was a glitch.

**Comment by aerugo** [comment]
Closing for now.
