### ISSUE TITLE
Random timeouts happening during use

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#234]
We are having problems with timeouts on use, which are intermittent and seem to happen anywhere on the platform.

**Comment by Powersource** [comment]
Old issue on this for reference https://github.com/Edgeryders-Participio/realities/issues/194

Looking at that issue and checking keycloak, we still seem to have the same settings that worked up until ~saturday. Really weird.

@aerugo Are other people than you having the issue? What's your browser and version? Do you select "remember me" when logging in?

**Comment by aerugo** [comment]
Ah this issue is actually not about the log-out thing, but about that this happens randomly when people are using the platform:

<img width="1611" alt="5c0ec69c1b7bf2c27d7f02736311f2633d0afd702770def03857b6e73a73c432" src="https://user-images.githubusercontent.com/7785081/116871441-8a077500-ac14-11eb-8ad2-7df358e2681e.png">

**Comment by aerugo** [comment]
But regarding the session time thing @Powersource, okay - let's ignore it for now until someone else complains.

We still need to fix that the site times out on heavy use though.

**Comment by Powersource** [comment]
Ok oops. Made a new issue for that one https://github.com/Edgeryders-Participio/multi-dreams/issues/236

**Comment by aerugo** [comment]
We are hoping that this was fixed by adding more cloud.
