### ISSUE TITLE
Style Keycloak login screen

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#253]
We want to change the following:

- There should be a much more prominent “Register” flow - now it is hidden below the login screen
- We want to style the login screen as close to Dreams as possible

**Comment by Powersource** [comment]
I think we want to use this tool I found a few weeks ago https://github.com/InseeFrLab/keycloakify to be able to generate the theme using react

I think we'll also want to create a docker image that combines the default keycloak docker image with our theme files. And hopefully most of this including deployment can be automated.

**Comment by aerugo** [comment]
Cool beans! 🥜

**Comment by skoteskote** [comment]
I wonder if we wanna switch Register and Login completely, so the first thing you see is the Register view and the Login option at the bottom? This is quite common nowadays

**Comment by Powersource** [comment]
Related https://github.com/InseeFrLab/keycloakify/issues/6

**Comment by aerugo** [comment]
We are ditching Keycloak.
