### ISSUE TITLE
Fix realities support for custom domains

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#254]
Right now the realities list here is mostly empty https://dreams.blivande.com/realities . But I would expect it to have the same content as https://realities.platoproject.org/blivande . Turns out it's because it parses only the subdomain to figure out the org, so it thinks the org is "dreams", and so this link is the one that shows the same content as the first link https://realities.platoproject.org/dreams

Until this is fixed, you can use the regular dreams.wtf with subdomains to access your realities, like this https://blivande.dreams.wtf/realities

**Comment by Powersource** [comment]
The dreams apollo client already supports this so we should just steal/combine with the logic there

**Comment by aerugo** [comment]
Future of Realities in the app is unclear, closing for now.
