### ISSUE TITLE
Add Plato Beta-info on landing page

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/multi-dreams#260]
Landing page https://dreams.wtf/ need to have information about Plato being in a Beta-stage. 

For example: "Plato is currently in an open beta version. There are bugs and features will change continually. The platform should not be used for mission-critical projects, and we do not allow for-profit organizations to use it at the moment. If you want to try it out please write us on info@platoproject.org"

**Comment by gustavlrsn** [comment]
Fixed in ee421ad
