### ISSUE TITLE
Assigning a dream to a Guide

### ISSUE THREAD

**Issue by DiarmaidEverycs** [Edgeryders-Participio/multi-dreams#267]
Hey peeps, I was trying to find a way to assign a guide to a specific dream on the platform - is this possible?

**Comment by aerugo** [comment]
No, it is not. In these cases it might actually be easier to just add them
as a co-creator of the Dream as it achieves the same functionality for them?

**Comment by DiarmaidEverycs** [comment]
Sounds good
