### ISSUE TITLE
Invite and login emails should be custom for org

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#272]
We need to be able to have custom emails based on which org the activity came from. 

Examples:

 - Invitation email to org/collection needs to contain org name and inviting user name
 - Comment notification needs to include org name
 - Registration confirmation email should include custom domain and org name when registering on "whitelabel" org

**Comment by aerugo** [comment]
After seeing how confused people are by the invite emails when we add them at Frihamnstorget, I am bumping this in priority.

Let’s think about how we can make this work. Ping @Powersource and @gustavlrsn

**Comment by Powersource** [comment]
Not very optimistic about how simple or clean it would be to do this.

Like we've talked about before, having a realm for each org would let us set a custom email theme for each org. But that alone wouldn't even get us all the way, which is to make it custom for each user.

Most promising thing I've found is https://dev.to/leamsigc/how-to-customize-the-keycloak-email-3d91 "In the email you have access to the user `${msg("greetingMessage", user.firstName, user.lastName)?no_esc}`". This might mean that we would be able to e.g. when user Alice invites user Bob, we could add Alice as an attribute on Bob's account and then get that when rendering the email template.

More related links on this

* https://github.com/holisticon/keycloak-theme-sample/blob/master/src/templates/email/messages/messages_en.properties
* https://github.com/holisticon/keycloak-theme-sample/blob/master/src/templates/email/html/email-verification.ftl
* https://github.com/keycloak/keycloak-documentation/blob/master/server_development/topics/themes.adoc
* https://stackoverflow.com/questions/50562384/keycloak-templates-available-variables
* https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
* https://github.com/zonaut/keycloak-extensions/tree/master/theme-minimal

**Comment by aerugo** [comment]
In that case, I think we need to have two cases.

1) We need to make the general invite email clearer. This is mostly a
matter of formatting and explaining more clearly what the platform is and
why you might have been invited.

2) We need to start exploring how to set a private realm for orgs paying
the premium. If we say that the cost of a premium subscription to Plato is
100 EUR per month, and that allows you to have a custom domain, your own
login options, connection to your own SSO, custom invite emails, a white
label platform, and eventually connection to OpenCollective - then I don’t
worry a about topping out at 300 realms. This also allows us to down the
line sell Plato to municipalities with BankID as an additional  premium.

Could you start exploring moving the Borderland org to its own realm, and
then setting that realm to only allow login through the Borderland keycloak
as a provider? Once we know that works, we should automate the process, and
then move CoBudget to their own realm.
