### ISSUE TITLE
Tag feature not working properly

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#279]
Steps to reproduce:

* Go to https://kiezburn.dreams.wtf/kb21
* Choose tag "archery"
* Result: Dream with tag is shown first, but also one "page" of other dreams without it

Further bugs:

* Go directly to https://kiezburn.dreams.wtf/kb21?tag=archery
* Now only the archery dream is shown
* Pick another tag which contains at least two dreams, like "Art". Only "Art" dreams are shown.
* Now pick a tag with one dream, like "Blockchain". Now the only blockchain dream is shown, but also three art dreams and the blockchain dream is shown twice.
* 
<img width="1485" alt="Screenshot 2021-06-18 at 21 45 34" src="https://user-images.githubusercontent.com/7785081/122609607-9178c580-d07e-11eb-88d5-a8e922106ccf.png">

I am not sure if these are connected, separate into two issues if not.

**Comment by Powersource** [comment]
lol found someone with the same issue but of course they didn't say how they fixed it :P https://github.com/apollographql/apollo-client/issues/7677
