### ISSUE TITLE
Search index should be automatically created

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#281]
Text search is working for me in production but not locally. When inspecting with mongodb compass it seems an index is missing.

From digging in the mongo/mongoose docs a bit it seems this line should be enough to create the index, but it doesn't seem to for some reason.

https://github.com/Edgeryders-Participio/multi-dreams/blob/7a53229d419494ea6cff9b8f296735c70c13e3f7/api/database/models/dream.js#L81

In the meantime I'll just manually create the index using compass but it'd be good if this was automated.

**Comment by aerugo** [comment]
Closing this for now as we are replacing mongoose.
