### ISSUE TITLE
Allowing a cost of 0

### ISSUE THREAD

**Issue by DiarmaidEverycs** [Edgeryders-Participio/multi-dreams#285]
So we told people to register for the dreams platform even if they were unsure what their budget was going to be or whether the event was going to go ahead (As an aside, the response from the community was great - we had over 60 dreams submitted in the end, under pretty short notice).

Some of the dreams turned out to not have any budget requirements - e.g. https://kiezburn.dreams.wtf/kb21/60c23bb6949852002d730cf7 - he is doing a performance without any costs (as we do not fund travel too and from the event).   

When we approve this for granting, because there is no budget, you get this:
![image](https://user-images.githubusercontent.com/38034266/122886383-34139b80-d340-11eb-927a-8b990123c1bf.png)

Where it looks like Lulu has not been approved.   If you instead add a budget to the dream:
![image](https://user-images.githubusercontent.com/38034266/122886526-573e4b00-d340-11eb-8278-e6203b5b5f1f.png)
Then we get the desired behaviour where the dream is approved and 100% funded.
![image](https://user-images.githubusercontent.com/38034266/122886640-6de4a200-d340-11eb-80b6-56ee4c9f98db.png)

Trying to set a budget of zero is not allowed.   
![image](https://user-images.githubusercontent.com/38034266/122886796-8f458e00-d340-11eb-9cc6-c5d3a213f409.png)

We can always work around this, in the same way as I have for the Lulu dream example here - once approved, we put in a tiny budget on both sides so that people can see that it is 100% funded.   But I think it would be a good feature to allow people to set a budget of 0 explicitely.

**Comment by aerugo** [comment]
I’ve fixed it now so that adding budget items with 0 is allowed. However,
you won’t get the desired effect because a dream with 0 funding and 0
budget will still not appear as funded. But I guess there would be no harm
in displaying the progress bar as complete in this case, let’s consider.

**Comment by aerugo** [comment]
@gustavlrsn - what do you think?

**Comment by DiarmaidEverycs** [comment]
Yeah, we would like to just show those dreams as completely funded as advertisement that they exist. Maybe have it as another setting - whether dreams which have a budget of zero are considered funded or not
