### ISSUE TITLE
Submitting multiple broken guidelines

### ISSUE THREAD

**Issue by DiarmaidEverycs** [Edgeryders-Participio/multi-dreams#286]
Another request

We have defined a series of guidelines for dreams, and when I am reviewing a dream, I can use the review monster to flag that a guideline has been broken.   But sometimes a dream will break more than one guideline, and I would like to be able to flag both of them.

![image](https://user-images.githubusercontent.com/38034266/122908971-008f3c00-d355-11eb-9f08-c542a3cbab69.png)

In this example, we can see that the dream breaks two guidelines - it's budget is not specific enough, and the total cost for transport is greater than 20%.   

![image](https://user-images.githubusercontent.com/38034266/122909304-59f76b00-d355-11eb-89e0-883b2a058468.png)
But when we go to report the second, we are not able to, it just says that the answer has been recorded.

It would be great if it just repeated the "Does this dream comply with all other guidelines?" question, until you said no.

**Comment by DiarmaidEverycs** [comment]
Fixed. Thank you.

**Comment by aerugo** [comment]
@DiarmaidEverycs - are you sure? I don't think we fixed this.
