### ISSUE TITLE
Only able to fund in integer units

### ISSUE THREAD

**Issue by DiarmaidEverycs** [Edgeryders-Participio/multi-dreams#299]
When you are trying to fund a project, it is only allowing you to fund in integer units.
![image](https://user-images.githubusercontent.com/38034266/123112942-6f948f80-d43e-11eb-95ef-e4586e0043a0.png)
This is also happening when you try to set a budget, or to set the maximum amount per dream, but not when you set the money each person has.

**Comment by aerugo** [comment]
Gotcha, thanks for the report. We will look into it at some point!
