### ISSUE TITLE
Able to fund more than the maximum amount per dream

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#301]
When you are setting up the dream platform, you are able to set a maximum amount per dream that each user can fund.   We have that set to 3 euro at the moment.
![image](https://user-images.githubusercontent.com/1898086/123239759-f9e10000-d4df-11eb-81cf-66463721e01f.png)

When you go to fund a dream, this amount is respected and you are not allowed to fund more than that to the dream:

![image](https://user-images.githubusercontent.com/1898086/123239871-14b37480-d4e0-11eb-8812-3afd71321f4b.png)

But it is possible to fund a dream the maximum amount, then click on the Fund button again, and fund it again.![image](https://user-images.githubusercontent.com/1898086/123240133-53e1c580-d4e0-11eb-9a86-fc7becdf3523.png)

![image](https://user-images.githubusercontent.com/1898086/123240230-6bb94980-d4e0-11eb-9edf-d773824792d3.png)

![image](https://user-images.githubusercontent.com/1898086/123240300-7c69bf80-d4e0-11eb-95f2-54ca43ba523c.png)

**Comment by gustavlrsn** [comment]
Looking at this

**Comment by gustavlrsn** [comment]
Fixed in fee911a
