### ISSUE TITLE
User does not see the funding button

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#303]
We have a user who is unable to see the funding button for the dreams. 

![NoFundDream](https://user-images.githubusercontent.com/1898086/123424430-1e60d900-d5c1-11eb-8106-e39dff738ff0.jpg)

The user is registered on the platform, and has her money set correctly
![image](https://user-images.githubusercontent.com/1898086/123424719-831c3380-d5c1-11eb-9a6c-e87617dd8876.png)

Any chance you could figure out what is happening?

**Comment by aerugo** [comment]
Could you ask her to check if the problem persists if she logs on with
another device, like her phone?

**Comment by Diemo-zz** [comment]
She says that the problem persists even after she tried with a phone. We also had a second user report the same problem on Facebook - he has not replied to me yet though about whether it worked on a different device.

**Comment by aerugo** [comment]
Do these two users have the problem with the same dream? Or different
dreams? Can they see the funding button for other dreams?

**Comment by Diemo-zz** [comment]
She can't see the funding button on any dreams.

**Comment by aerugo** [comment]
@gustavlrsn, any idea what might be going on here?

**Comment by Powersource** [comment]
For reference here's the logic that decides when to display the button

https://github.com/Edgeryders-Participio/multi-dreams/blob/6b3435ea3ca4eb9817b09f1294edc77cfecd5051/ui/components/Dream/Sidebar.js#L143-L148

**Comment by Powersource** [comment]
According to keycloak she's userId `6306aa54-c6e7-4ab5-a1b4-3bc62c6f5630`. But that id doesn't seem to have an orgMember for kiezburn. From the screenshot it looks like she's an eventmember though. Can people be an event member without being an org member? I'll dig a little bit more but Gustav should maybe look at this.

**Comment by aerugo** [comment]
Kiez added a lot of members at once, resulting in that they got throttled: https://github.com/Edgeryders-Participio/multi-dreams/issues/302

Perhaps that's what happened with a few members - they got added to the collection but failed to get added to the org and there was no loop to make sure they got added once the endpoint became available again?

**Comment by Powersource** [comment]
Something like that sounds likely. I'll leave this to Gustav since he knows the invite code better.

**Comment by aerugo** [comment]
@Diemo-zz, if our theory is right, the problem might be solved by adding Burning Sparrow to the Org manually. Go to the Org overview, then Members -> Invite and add her email.

**Comment by DiarmaidEverycs** [comment]
I'll try this, but I did delete the user from the event, and re-add her.   I would have thought that she would have been added to the Org then.

**Comment by DiarmaidEverycs** [comment]
![image](https://user-images.githubusercontent.com/38034266/123675145-b02b4900-d842-11eb-9daa-12b308377732.png)
So I dont think that this is the case, but when did you check to see whether she was a member of the org? If members are gotten in order that they are added (which it appears like they are) then she should have been a member of the org since ~1.55 on the 26th of June.

Was just talking to her, and she is still not able to see the Funding button under that account. But she is a member of both the org and the event.

**Comment by Powersource** [comment]
When I checked again later she seemed to be an orgmember. Idk if i checked
the wrong way the first time.

Jacob

**Comment by gustavlrsn** [comment]
Looking at this. Can at least confirm that an org member exists for kiezburn and that keycloak user id, created 3 days ago.

**Comment by gustavlrsn** [comment]
Ok, so what I can see is that the initial org member account that I mention above has no event membership.

The replacement account has an event membership, that has been allocated 10 EUR and those have been contributed to two different dreams (5 EUR each) ([`605112ac4e7fb0002cf5a0f6` ](https://kiezburn.dreams.wtf/kb21/605112ac4e7fb0002cf5a0f6) (the dream in question) and [`60cc9d3e9cbf16002c5b7bdf`](https://kiezburn.dreams.wtf/kb21/60cc9d3e9cbf16002c5b7bdf)).

@DiarmaidEverycs

**Comment by Diemo-zz** [comment]
The funding button is still missing from her account (the Burning Sparrow account), even though I set it to have a balance of 1 EUR.

From our perspective it is resolved, yes. We just registered her under a different email.

**Comment by gustavlrsn** [comment]
Gotcha. 

I can't find an event/collection membership for the Burning Sparrow account, could you confirm if you still see it in the collection membership list with a balance? Something weird going on that we should fix if it is still there

**Comment by Diemo-zz** [comment]
Yup, she is in the list for both the event and the . I can also still update her balance for the event.

**Comment by Diemo-zz** [comment]
We have another user with the same issue.   I will email you the the email address.

**Comment by gustavlrsn** [comment]
Found a bug where invited users who were member of another org did not get a new org membership causing this issue, fixed in fbd2411e3a0587ffdb567f3ae843e6b51bb1c64b.
