### ISSUE TITLE
We have pagination but no search

### ISSUE THREAD

**Issue by DiarmaidEverycs** [Edgeryders-Participio/multi-dreams#307]
The pagination is great - it was really slow to view the members before. But now I need a way to find members without loading up all ~860 of them.   Could you implement a search by email address please?

**Comment by aerugo** [comment]
@Powersource - I guess this would take a while to implement? But I also see that this implementation doesn't really work with that many users, as you need to be able to find specific ones to give them admin rights and allocate funds! 

Either we find a fast way to do search, or we set the config to 1000 records per page as a quick fix until we implement search filtration.

**Comment by DiarmaidEverycs** [comment]
Yes, please.   From a user point of view I would rather wait the 10 seconds it took to load the members than have to click on the "Load More" button a million times.

**Comment by aerugo** [comment]
Alright, I just set the pagination limit to 1000 records for collections. Can you verify that it works @DiarmaidEverycs ?

**Comment by DiarmaidEverycs** [comment]
Much better, thank you
