### ISSUE TITLE
Viewing number of unverified users

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#309]
When you look at the list of users, you can see whether or not the user has been verified.
![image](https://user-images.githubusercontent.com/1898086/123676535-5b88cd80-d844-11eb-81ca-80331618e819.png)
It would be nice if we could see 2 things here:
1) How many users are not verified in total
2) How many users still have 10 EUR in their account

We want to know how many people have gone onto the platform, and how many people still have to donate, so that we can send an email out saying something like:

Only 30% of you have voted - voting ends in 3 days. Please make sure to submit your vote before the deadline of XXX.

I would put this in the about page.
![image](https://user-images.githubusercontent.com/1898086/123676962-d7831580-d844-11eb-83fa-ca22b92c1df1.png)

**Comment by aerugo** [comment]
I agree we should have this. Until we do, might I propose a quick-fix if you have a spreadsheet-savvy person on the team? 
Copy the whole member's table and paste it into a spreadsheet, then do some simple spreadsheet-wrangling to filter out users that are not verified (use REGEXMATCH for "(not verified)") and users with >0 EUR (first remove the "EUR" string, then cast the string into a number and sort).

**Comment by aerugo** [comment]
I have noticed that selecting the rows does not always work, but if you do a CRTL-A on the collection member page, that copies the table in a way that works when you paste it into a Google sheet.

**Comment by aerugo** [comment]
Closing this in preparation for more general overhaul.
