### ISSUE TITLE
Showing percentage funded

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#310]
So, this is my current view of the dream platform
![image](https://user-images.githubusercontent.com/1898086/123700223-7bc68580-d860-11eb-9c0e-856c4c787fce.png)
And we have the dream there that is 300% funded, but what is actually happening here is that this dream has a minimum budget of 0, which shows to infinity so I set it to a minimum of 1 and prefunding of 1.

(dream: https://sites.google.com/view/kiezburn/dreams)

Could we change it so that it shows the percentage of the stretch goal that is funded, with a bar where the minimum goal would be instead?   Or modify it in such a way as to show how much of the minimum budget is funded, and how much of the stretch goals have been funded/are left to be funded?

Possibly solved by https://github.com/Edgeryders-Participio/multi-dreams/issues/306 - if that shows minimum, stretch and current funding.

**Comment by aerugo** [comment]
@gustavlrsn, could we make a little update to the progress bar so that it calculates by max funding and indicates the stretch goals point with a little ticker symbol - like on the old Dreams platform?

**Comment by gustavlrsn** [comment]
Yeah, let's add that back in!
