### ISSUE TITLE
No longer able to see transactions

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#311]
![image](https://user-images.githubusercontent.com/1898086/123795006-c89f7000-d8e3-11eb-8f38-2837aceefd78.png)

Our transactions have disappeared

**Comment by gustavlrsn** [comment]
Hmm, might be that we're not deleting contributions/transactions when we delete event members, and the schema for transactions require an event member for every transaction, if this does not exist, it will create a graphql error and return nothing. 

Easiest fix would probably be to not require an eventMember in the schema for transactions/contributions and adjust the ui code to not expect a member/user there (and show deleted instead)

**Comment by Diemo-zz** [comment]
![image](https://user-images.githubusercontent.com/1898086/123818297-28ecdc80-d8f9-11eb-951f-9db3d13ad3f3.png)

Now we can't see the members either :/.

**Comment by gustavlrsn** [comment]
Working on a fix

**Comment by gustavlrsn** [comment]
@Diemo-zz looking closer at your screenshots and your error message I can see you are running an old version of the frontend. I'd try a hard refresh to have these two pages working again

**Comment by Diemo-zz** [comment]
I can see the members now, but trying to invite people is giving me a 409 error.

![image](https://user-images.githubusercontent.com/1898086/123833051-3f4d6500-d906-11eb-9e3a-3911181f166c.png)

{"errors":[{"message":"Request failed with status code 409","locations":[{"line":2,"column":3}],"path":["inviteEventMembers"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"config":{"url":"https://auth.platoproject.org/auth/admin/realms/plato/users","method":"post","data":"{\"username\":\"<email>\",\"email\":\"<email>\",\"requiredActions\":[\"UPDATE_PROFILE\",\"UPDATE_PASSWORD\"],\"enabled\":true}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","Authorization":"bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJWb2MyRGMtaDBiQXhpSXVvYzlhN2YybXZPNmJOanlzWlg5QTZaRmtFdUU0In0.eyJleHAiOjE2MjQ5ODM2NjYsImlhdCI6MTYyNDk4MzYwNiwianRpIjoiNjIyZjJkNmQtM2MyYy00Mjk2LWFlNzQtMGRjZDc4OTYwZDFmIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnBsYXRvcHJvamVjdC5vcmcvYXV0aC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiMDI2MzBkOWEtYzc3ZC00NWZkLTgxZjktZGU3YjI3MjhlZWNhIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6IjVlY2RkM2MwLTNiY2EtNDU1OS1iYjgzLTY1NDNkMGQwZjA5MCIsImFjciI6IjEiLCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKYWNvYiBLYXJsc3NvbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkphY29iIiwiZmFtaWx5X25hbWUiOiJLYXJsc3NvbiIsImVtYWlsIjoiamFjb2Iua2FybHNzb245NUBnbWFpbC5jb20ifQ.H4VlY8b_LLRRXSsfZc952Ph9yXmNA1YtTSRS2aUML8Ko21OBcD1ZklryQ0hIvcObKKvq_y1y94w7RAwVtl1Ql--kdYzxjMOoP8Af9lNCzAV38HBGAFPrTp5ChBlFV1-nS1TPV-gDRRvwhUCLIeqIAwvEW4DL3Rmvh27qRyp3UlsF-swNv4xstwksb4ImnGIzdZ65Tsn0GaVGElvyWj8uiqVkf15NNkweE975rraKmcMMxJQhK2r4CAsaOP-zSzfI1VM9wGxRg8nd9T-V-Z8wd-ZDS9jQmMGeyy1gxNTf59RobrBie4WpaUU3iJw7436mCykFXcvTyrrrf5kcVoCqoA","User-Agent":"axios/0.21.0","Content-Length":138},"params":{},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}}}],"data":{"inviteEventMembers":null}}

**Comment by gustavlrsn** [comment]
@Diemo-zz have not seen that one before. From some quick googling it seems like Keycloak can return a 409 error when adding a user that already exists.. Could that be the case here?

**Comment by Diemo-zz** [comment]
I think it might have been related to the using the old frontend. It is working again now either way.
