### ISSUE TITLE
Show all contributors to dreams

### ISSUE THREAD

**Issue by skoteskote** [Edgeryders-Participio/multi-dreams#315]
Display everyone that has funded / contributed to a dream in a public list. Probably under the funding progress bar? 

A problem is how to display this in case of many contributors. A quick and dirty solution is to cap the list to just show the ~10 most recent contributions. We have an org whose use case requires this feature, and they will only have 6 people funding (but hundreds of members.) We can implement the quick and dirty solution now, and implement an expandable/paginated list later.

**Comment by gustavlrsn** [comment]
Added a list of 10 most recent contributions: 
![image](https://user-images.githubusercontent.com/1552194/127545929-91179c0a-b99e-4ec0-a66c-9bc8fac937c7.png)
