### ISSUE TITLE
Seeded shuffle of dreams

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#32]
To make the dreams more equal in terms of the attention they will get in granting it would be good to have the order of dreams shuffled/randomized.

But this would also make it a bit annoying to use, if everytime you reload you get a new random order. For this reason we can use a seeded shuffle, and use something like your user id as seed, to give the user a consistent shuffle. However it would be reshuffled whenever something new is added or removed, but this should not be such a big problem when granting has started and things are not generally added or removed, and this is when a consistent order is most beneficial, i.e. you are a user trying to look through all dreams to know which ones to give your grants to.

**Comment by Powersource** [comment]
I feel like we could use something similar here to how we do with the sorting of custom fields.

I'm thinking like: When a dream is created, we set a field `position` on it to `Math.random()`, a double somewhere between 0 and 1. We simply sort the dreams depending on the `position` they have. Then things would get a random position, and things wouldn't shuffle around much when a new dream is added.

**Comment by aerugo** [comment]
I think the most useful behavior would be that:

- Dreams appear to be sorted randomly but the random order persists on
reload
- However, the random order is periodically reseeded somehow, so you don’t
see the same Dreams on top when log on a few days later

Perhaps this could be achieved with the random position double + a double
between 0 and 1 generated by seeding a random function with the day or week
number of the year. If the sum is larger than 1, the position becomes sum -
1. That way the randomly sorted Dreams will reshuffle once per day.
