### ISSUE TITLE
Giant spinner on pages load

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#327]
When pages are loaded, the spinner goes fullscreen and overlays the page.

**Comment by Powersource** [comment]
Oh shit that's really big haha. Testing it now I can reproduce in prod, but when loading the same dream ( https://dreams.blivande.com/frihamnstorget/606b09de386d4a002c6e96b8 ) on localhost the spinners are normal size :thinking:

**Comment by gustavlrsn** [comment]
It is probably dynamically specified tailwind classes that the css file size reducer does not pick up, can add these to the whitelist

**Comment by Powersource** [comment]
Seems fixed by https://github.com/Edgeryders-Participio/multi-dreams/commit/4b311789486d2afee7d4a3152d9d30a6cd45c269 !
