### ISSUE TITLE
Improved Markdown support

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#331]
Our support for Markdown is a little patchy at the moment. 

Compare this: http://markdown-it.github.io/
And this: https://testingprotocol.dreams.wtf/my-test-event/613f4b96504e13002c0f7e8b

Priorities:

- [ ] Change heading style so headings are not larger than question titles
- [ ] Add padding around paragraphs, lists, and list items
- [ ] Indent lists
- [ ] Support sub-lists
- [x] Support code blocks 
- [ ] Support tables
- [ ] Format images to reasonable height
- [ ] Add padding around images

**Comment by Powersource** [comment]
We already support code blocks. We don't support tables because I think that's a GFM feature but I think that's easy to enable with the module we're using.

**Comment by Powersource** [comment]
@aerugo guessing you still want this?

**Comment by aerugo** [comment]
Let’s see how we feel after the wysiwyg is in place.
