### ISSUE TITLE
Update how information is shown in the "Budget" section

### ISSUE THREAD

**Issue by tomomiq** [Edgeryders-Participio/multi-dreams#340]
Goal: Increase clarity of what's being proposed, money-wise. 

Key changes for the co-creator: 
Communicating what they have already secured access to is split between Existing funds and Non-monetary contributions, instead of all under "Existing funding and resources". 

![ ](https://user-images.githubusercontent.com/1287179/135071088-df990a14-920a-49c9-a4d9-1943529efde6.jpg)

**Comment by Powersource** [comment]
I don't remember exactly from the meeting, did we decide to actually do this or we wanted to think it over a bit more?

**Comment by aerugo** [comment]
I think we can still implement this as Tomomi suggests. We were mainly
debating if the existing funding should be included in the progress bar.
These updates still make sense. Tomomi - we also wanted to add some copy
clarifying that the existing funding gets added to the progress, correct?

**Comment by Powersource** [comment]
yeah i've written to her to clarify the other changes we wanted

**Comment by tomomiq** [comment]
Yes, sorry, had a quick chat with the team. 

Update: 

![Image 2021-09-28 at 3 31 16 PM](https://user-images.githubusercontent.com/1287179/135096835-64c578df-fba3-4105-84db-e4e70ea641b6.jpg)
