### ISSUE TITLE
Inviting members does not work 

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#417]
Steps to reproduce:

- Invite a member by email to a collection

Result:

No email is sent

**Comment by gustavlrsn** [comment]
@aerugo in lieu of a proper invite that you can accept or not (which we never had), I guess the simple solution for right now is sending an email, something like this?

> Subject: {adminName} invited you to {orgName}'s {collectionName} collection on Cobudget
> Body: Click here to sign in: {link}

**Comment by aerugo** [comment]
Yup, that would work.

**Comment by gustavlrsn** [comment]
Fixed. Slightly altered to not include a magic login link for a simpler solution, also better for when we don't only provide magic links
