### ISSUE TITLE
Creating new tags does not work

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#419]
Steps to reproduce:

- As an admin, try adding a new tag to a bucket

Result:
No tag is added

**Comment by aerugo** [comment]
@Powersource - creating a tag does work now, but adding that tag to other buckets does not. Let's keep track of this here before closing.

**Comment by Powersource** [comment]
hmm i tested both of those things and they worked for me. will have to test in prod

**Comment by aerugo** [comment]
It seems to work now. When I tested, only creating tags worked.

There is however a UX problem with that one has no way to see which tags are available.
Is there a way to have the dropdown show with all available tags when the user clicks the field? And then have it filter on typing?

**Comment by Powersource** [comment]
that's how it works for me in prod atm
