### ISSUE TITLE
Deleting bucket does not work

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#423]
Steps to reproduce:

- Delete bucket, as owner or admin

Results:

User is sent to an empty org screen with 0 collections. If she then goes back to her org and the collection she was in before, the bucket she tried to delete is still there.

**Comment by gustavlrsn** [comment]
- [ ] After deletion send to correct collection route

**Comment by gustavlrsn** [comment]
Fixed with a soft delete
