### ISSUE TITLE
Settings do not update without reload

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#424]
Steps to reproduce:

- Go to Settings
- Change the value of "Registration policy" drop-down
- Press save

Result:

Dropdown switches back to old value, making the user think it was not changed. 
It is changed however, but this is not seen without reloading.

**Comment by gustavlrsn** [comment]
Note: Dropdowns not updating

**Comment by gustavlrsn** [comment]
Fixed
