### ISSUE TITLE
Search sends user to empty org

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#426]
Steps to reproduce:

- Search for anything in a collection

Result:

User is sent to what seems to be an empty org screen, without their collections.

<img width="2302" alt="Screenshot 2021-11-09 at 18 38 19" src="https://user-images.githubusercontent.com/7785081/140975831-44ce59cb-9df6-468b-8da2-cf0b222598c6.png">

**Comment by gustavlrsn** [comment]
Fixed
