### ISSUE TITLE
Collections are now called events again

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#429]
We changed all mentions of "event" to "collection", but this seems to have been reverted in the new version.

**Comment by gustavlrsn** [comment]
@aerugo where?

**Comment by aerugo** [comment]
<img width="1285" alt="Screenshot 2021-11-09 at 19 39 20" src="https://user-images.githubusercontent.com/7785081/140984666-a1b9ee67-e275-4f35-8908-de0b67da6934.png">

**Comment by gustavlrsn** [comment]
Ops, that was never fixed. Changed to Collection now.
