### ISSUE TITLE
Design coupling

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#49]
Design (`Layout.js` component) is coupled strongly with other modules.
This makes it difficult to test sub components and get them to render such as using a `storybook`

**Comment by rootux** [comment]
Here are some screenshots trying to test a single componet using `storybook` as you can see it doesn't render well. Ideally we would want to simply import a component and have the "Themeing" of the app works out of the box

<img width="705" alt="Screen Shot 2020-06-13 at 21 37 48" src="https://user-images.githubusercontent.com/1032526/84576537-21c26180-adbe-11ea-9554-707acff6c6f9.png">
<img width="940" alt="Screen Shot 2020-06-13 at 21 37 55" src="https://user-images.githubusercontent.com/1032526/84576538-22f38e80-adbe-11ea-81cf-aaba5f7b3dd7.png">

**Comment by aerugo** [comment]
Closing this for now as it has not seen any activity and doesn't seem to hinder development much.
