### ISSUE TITLE
Basic data model/collection naming

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#57]
Here is our current data model including the not yet implemented organizations collection.

![image](https://user-images.githubusercontent.com/1552194/86609529-546e0d00-bfac-11ea-9e26-9dc3674cb9c7.png)

I suggest renaming the **members** collection to **memberships** ("members" made more sense before when there was no users collection). We have also talked about renaming **events** to **funds**.

**Comment by rootux** [comment]
Looks good.
I don't understand the logic behind changing `events` to `funds`

**Comment by gustavlrsn** [comment]
> Looks good.
> I don't understand the logic behind changing `events` to `funds`

I think the logic was that a potential common usecase could be to use the dreams process/platform to fund projects within your community or organization that are not necessarily connected to a single event, like this usecase: https://dreams.blivande.com/dream-generator. Making it more of a fund or funding round.

**Comment by gustavlrsn** [comment]
Also for reference, here is a [sketch of the plato terminology](https://user-images.githubusercontent.com/1552194/86609529-546e0d00-bfac-11ea-9e26-9dc3674cb9c7.png)

**Comment by gustavlrsn** [comment]
Added some more thoughts in the thread above.

**Comment by aerugo** [comment]
I would like to return to discussing this model again.

One thing that has become clear when seeing groups use Dreams is that there is a very clear need for the tool outside of the event setting. It is even quite likely that permanent places and small communities will be the most prominent users. In light of this, I am starting to think that we might want to rename "Event" to "Collection".

This is being discussed here: https://forum.blivande.com/t/plato-terminology/1188/6?u=hugi

**Comment by aerugo** [comment]
I'm closing this issue as this is a discussion better suited for the forum.
