### ISSUE TITLE
Login + Create event text is hidden

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#62]
Top right screen - user can't see the "Create event" button
Same for Login (For guest user) - not visible

<img width="330" alt="Screen Shot 2020-07-08 at 14 31 11" src="https://user-images.githubusercontent.com/1032526/86913803-d33b8500-c127-11ea-98c9-8611ca72758b.png">

**Comment by gustavlrsn** [comment]
It's apparently the link color that is white here 😆, spotted by @LudwikJaniuk 👀
