### ISSUE TITLE
Integrate a migration framework

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#64]
# Why
This would help us with:
- Seeding the database (Creating the initial organization, Creating some admin user for that organization)
- Handle future production migration

# Suggested out of the box solutions
- [migrate mongo](https://www.npmjs.com/package/migrate-mongo) - Handles changelog on the db level
- [migrate - Abstract migration framework for node](https://www.npmjs.com/package/migrate) - handle changelog in a local file (.migrations)

Since it's a very simple module (Up, Down, Load changelog) - I believe both solutions are okay. migrate mongo might be better since it keeps the current state on the db level.

Any thoughts @gustavlrsn @aerugo

**Comment by aerugo** [comment]
@gustavlrsn - did we ever implement migrations?
