### ISSUE TITLE
Assign Event Admin

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#67]
As `Organization admin` I want to be able to assign an `Event admin`

@gustavlrsn Can you assist with some UI mocks for this?

I'm thinking of doing it through the `Members` - When you go to the setting next to a user same like "Make guide" / "Remove guide" -> "Make event admin" / "Remove event admin"

**Comment by gustavlrsn** [comment]
Event admins can do this on the `Members` page currently:
![image](https://user-images.githubusercontent.com/1552194/87299699-ce524900-c50c-11ea-83b2-b5b22cd0efe9.png)

I guess we could let `Organization admins` do this (without being event admins) on the same page?

**Comment by aerugo** [comment]
This is now possible after the org setting feature was implemented.
