### ISSUE TITLE
System can easily break when deleting events - Delete event feature

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#79]
If an event is being deleted from the db - the system stops working.
We may get 404 - Organization not found - but it's actually an error of "Cannot return null for non-nullable field Member.event."

We should support deleting events from the UI to prevent this case from happening (By also cascade deleting all related entities)

**Comment by aerugo** [comment]
Agreed, and when we start allowing people to create their own orgs, this actually becomes very high priority.

**Comment by gustavlrsn** [comment]
Fixed in #98
