### ISSUE TITLE
Deleting an event

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#94]
Ability to delete an event (And cascade delete all the objects)
(Probably we should soft delete an event)
Add a UI in the "Edit event screen" with "Delete" - this would show a modal where the user need to enter the slug name to actually delete it

**Comment by rootux** [comment]
MVP 2 - In the future - add a button to do Hard delete after 90 days

**Comment by gustavlrsn** [comment]
Fixed in #98
